### ISSUE TITLE
0.3 Release Checklist

### ISSUE THREAD

**Issue by hmans** [hmans/three-elements#42]
- [x] Go through the documentation and update examples and documentation where necessary
  - [x] Document resource reuse
  - [x] Document custom camera 
  - [x] Document custom renderers
  - [x] `deg` shorthand
- [x] Test with some of the framework-specific codesandboxes
  - [x] Svelte
  - [x] Vue
  - [x] React
  - [x] Preact
- [x] Test how it behaves in the lit-shootybang demo
- [x] Test how it behaves in our... main project
- [x] Release it to NPM
- [x] Write blog post on hmans.co
